filebeat.inputs:
  - type: filestream
    id: flexrate-backend-logs
    enabled: true
    paths:
      - /logs/*.log
      - /logs/*.json
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true

output.logstash:
  hosts: ["logstash:5000"]
