version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: flexrate-mysql
    environment:
      MYSQL_DATABASE: flexrate
      MYSQL_USER: flexrate_user
      MYSQL_PASSWORD: strong_password
      MYSQL_ROOT_PASSWORD: root_pw
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:7.2
    container_name: flexrate-redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flexrate-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    restart: always

volumes:
  mysql-data:
