version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: flexrate-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:7.2
    container_name: flexrate-redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flexrate-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_URL: ${MYSQL_URL_PROD}
      MYSQL_USERNAME: ${MYSQL_USERNAME_PROD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROD}
      REDIS_HOST: ${REDIS_HOST_PROD}
      REDIS_PORT: ${REDIS_PORT_PROD}
    restart: always

volumes:
  mysql-data: