server:
  port: 8080

spring:
  application:
    name: flexrate-back
  config:
    import:
      - optional:file:./.env[.properties]
  datasource:
    url: ${MYSQL_URL_PROD}
    username: ${MYSQL_USERNAME_PROD}
    password: ${MYSQL_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 100000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
  data:
    redis:
      host: ${REDIS_HOST_PROD}
      port: ${REDIS_PORT_PROD}
  session:
    store-type: redis
    timeout: 1800
  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: redis
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    com.flexrate.flexrate_back: DEBUG
    org.hibernate.SQL: debug
    org.springframework: info
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method