server:
  port: 8080

spring:
  application:
    name: flexrate-back
  profiles:
    active: dev
  config:
    import:
      - optional:file:./.env[.properties]
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 100000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  session:
    store-type: redis
    timeout: 1800
  flyway:
    enabled: false
    locations: classpath:db/migration
  cache:
    type: redis
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      timeout: 5000
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretKey: ${JWT_SECRET_KEY}

logging:
  level:
    root: INFO
    com.flexrate.flexrate_back: DEBUG
    org.hibernate.SQL: debug
    org.springframework: info
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

security:
  allowed-origins:
    - http://localhost:3000
    - https://flexrate-front.vercel.app
    - https://flexrate.online/

fastapi:
  host: ${FASTAPI_HOST:localhost}
  port: ${FASTAPI_PORT:8000}

openai:
  model: gpt-3.5-turbo
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
